before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go fmt ./...
    - golangci-lint run -c .golangci.yml --fix
    - gofmt -s -r 'interface{} -> any' -w .
    - goimports -w .
    - gofumpt -w .
builds:
  - skip: true
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
