defaultBaseImage: gcr.io/distroless/static:nonroot
defaultFlags:
  - -tags
  - netgo
defaultLdflags:
  - -s
  - -w
  - -extldflags "-static"
  - -X main.version={{.Env.VERSION}}
defaultEnv:
  - GOPRIVATE=github.com/bitsnap/chargebee-api-client

builds:
  - id: chargebee-client-codegen
    main: ./main.go
